import Head from "next/head";
import Hero from "../Components/Hero";
import Articles from "../Components/Articles";
import Findus from "../Components/Findus";
export default function Home() {
  return (
    <div>
      <Head>
        <title>l.code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Articles />
      <Findus />
    </div>
  );
}
